name: t2tydna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core
  - python=3.10
  - pip

  # core libs
  - pytorch=2.3
  - numpy
  - h5py
  - mappy

  # Bioinformatics tools
  - filtlong=0.2.1
  - nanoplot=1.44.1
  - augustus=3.5.0
  - gffread=0.12.7
  - eggnog-mapper=2.1.13
  - flye=2.9.6
  - seqkit=2.10.0
  - quast=5.3.0
  - busco=5.8.2
  - minimap2=2.29
  - racon=1.5.0
  - medaka=2.0.1
  - bwa=0.7.19
  - samtools=1.21
  - ragtag=2.1.0
  - mummer4=4.0.1
  - pybedtools=0.12.0

  # R base
  - r-base=4.3
  - r-essentials

  # R packages
  - r-seqinr
  - r-data.table
  - r-ggplot2
  - r-viridis
  - r-ggextra
