#!/bin/bash

set -x

source ./config

cd $tmpdir

## backmapping
assemblies_clean="$inds.backmap.fa"
fasta=$assemblies_clean
assembler="flye"
if [[ $short_reads == "yes" ]]	
then
    #assembler=$(echo "$fasta" | cut -d"." -f2)
    echo "back mapping: $assembler"
    #conda activate bwa
    bwa index "$basedir/tmp/$fasta"
    bwa mem -t 8 "$basedir/tmp/$fasta" $seqdir/$inds"_1.fastq.gz" $seqdir/$inds"_2.fastq.gz" > "$mapdir/$inds.$assembler.sam"
    #conda deactivate

    #conda activate samtools 
    samtools  view -@8 "$mapdir/$inds.$assembler.sam" -o "$mapdir/$inds.$assembler.bam"
    samtools sort -l 1 -@8 -o "$mapdir/$inds.$assembler.srt.bam" "$mapdir/$inds.$assembler.bam"
    samtools index "$mapdir/$inds.$assembler.srt.bam"
    #conda deactivate 
fi
 #conda activate minimap2
 minimap2 -ax map-ont -t 8 "$basedir/tmp/$fasta" "$seqdir/$inds.filtlong.fastq.gz" > "$mapdir/$inds.$assembler.ont.sam"
 #conda deactivate

 #conda activate samtools 
 samtools  view -@8 "$mapdir/$inds.$assembler.ont.sam" -o "$mapdir/$inds.$assembler.ont.bam"
 samtools sort -l 1 -@8 -o "$mapdir/$inds.$assembler.ont.srt.bam" "$mapdir/$inds.$assembler.ont.bam"
 samtools index "$mapdir/$inds.$assembler.ont.srt.bam"
 #conda deactivate 
 
cd $mapdir

rm $inds".flye.sam" $inds".flye.bam"

rm $inds.$assembler".ont.sam" $inds.$assembler".ont.bam"
