#!/bin/bash

###########################################################
#			INITIALIZATION              	  #
#                                                         #
# This script initializes the environment for the sample  #
# processing pipeline. It loads configuration parameters, #
# sets up necessary directories. 			  #
###########################################################

basedir=$(dirname "$(pwd)")

config_file="$basedir/scr/config"

set -a

source "$config_file"

set +a

# Create output directories
genome_size="12500000"
mkdir -p  "$asmdir"  "$tmpdir" "$logdir" "$errordir" "$anndir" "$mapdir" "$telodir"

> "$logdir/latest" 

echo "$(date)" > "$logdir/latest"

echo "initialization complete :)"
