#!/bin/bash

set -x

source ./config

rounds=1

cd $basedir/tmp

assemblies_raw="$inds.flye.raw.fasta"

for fasta in $assemblies_raw
do
  	
    cp -r "$fasta" "$inds.tmp.fa"
    assembler=$(echo "$fasta" | cut -d"." -f2)

    # Long-read based polishing
    for i in $(seq 1 1 "$rounds")
    do
        echo "long-read based correction: step $i, assembler: $assembler"
        #conda activate minimap2
        minimap2 -ax map-ont -t 8 "$basedir/tmp/$inds.tmp.fa" "$seqdir/$inds.filtlong.fastq.gz" | pigz - > "$mapdir/$inds.sam.gz"
        #conda deactivate

	#conda activate racon
	racon "$seqdir/$inds.filtlong.fastq.gz" "$mapdir/$inds.sam.gz" "$inds.tmp.fa" > "$inds.racon_polished.${assembler}.${i}.fasta"
         #conda deactivate

	echo "got: $inds.racon_polished.${assembler}.${i}.fasta"

        rm "$inds.tmp.fa"
        rm "$mapdir/$inds.sam.gz"
        cp "$inds.racon_polished.${assembler}.${i}.fasta" "$inds.tmp.fa"

        if [ "$i" -eq "$rounds" ]
        then
            echo "Concluded polishing, converting: $inds.racon_polished.${assembler}.${i}.fasta to its final file."
            cp -r "$inds.tmp.fa" "$inds.racon_polished.${assembler}.final.fasta"
        fi
    done
    rm -f *.1.* *.2.* *.3.* "$inds.tmp.fa"
done


assemblies_raconpolished="$inds.racon_polished.flye.final.fasta"

for fasta in $assemblies_raconpolished
do
         echo "Medaka: $fasta"
	 assembler=$(echo "$fasta" | cut -d"." -f3)
         
	 #conda activate medaka
	 medaka_consensus -i "$seqdir/$inds.filtlong.fastq.gz" -d "$fasta" -o "$inds.medaka.${assembler}"  -t 8 -m "$model"
	 #conda deactivate
	 
	 ln -s "$basedir/tmp/$inds.medaka.${assembler}/consensus.fasta" "$basedir/tmp/$inds.medaka.${assembler}.final.fasta"

	 rm *.fai
	 rm *.mmi
   
done
