#!/bin/bash

set -x

source ./config

ref_pathfile=$(cat $tmpdir/$inds".sort.mash" | cut -f2 | head -1)

cd $tmpdir

#conda activate ragtag 
ragtag.py scaffold $ref_pathfile $tmpdir/$inds.flye.clean.fa
ln -s $tmpdir/ragtag_output/ragtag.scaffold.fasta $tmpdir/$inds.backmap.fa
#conda deactivate
