#!/bin/bash

set -x

source ./config

ref_pathfile=$(cat $tmpdir/$inds".sort.mash" | cut -f2 | head -1)

cd $tmpdir

#conda activate mummer 
nucmer --mum -l 200 $inds".backmap.fa" $ref_pathfile -p $inds".backmap-ref"
mummerplot --large --color --png $inds".backmap-ref.delta" -p $inds".backmap-ref"
rm *delta *rplot *gp *fplot
#conda deactivate
